name: Daily Contest Script

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule the workflow to run at 00:00 UTC daily
  workflow_dispatch:

jobs:
  run_contest_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Check if branch exists
        run: |
          branch_exists=$(git ls-remote --exit-code --heads origin automate-c-json-update || echo "")
          if [ -n "$branch_exists" ]; then
            git fetch origin automate-c-json-update
            git checkout automate-c-json-update
          else
            git checkout -b automate-c-json-update
          fi

      - name: Run contest.py script
        run: python scripts/contest.py

      - name: Check for changes
        id: git-diff
        run: |
          git fetch origin main
          changes=$(git diff --name-only main -- data/contests.json)
          echo "::set-output name=changes::$changes"

      - name: Install hub
        run: |
          # Install hub from GitHub releases
          HUB_VERSION=2.14.2  # Replace with the desired version
          HUB_OS=amd64  # Replace with the appropriate OS version

          wget https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-linux-${HUB_OS}-${HUB_VERSION}.tgz
          tar -xvzf hub-linux-${HUB_OS}-${HUB_VERSION}.tgz
          sudo mv hub-linux-${HUB_OS}-${HUB_VERSION}/bin/hub /usr/local/bin/hub
        shell: bash

      - name: Create Pull Request
        if: steps.git-diff.outputs.changes != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_branch="automate-c-json-update"
          pr_title="Automated Pull Request"
          pr_body="This pull request updates the JSON file automatically."

          # Create the pull request
          hub pull-request -m "$pr_title" -b main -h "$pr_branch" -m "$pr_body"
