name: JSON Schema Validation

on:
  push:
    paths:
      - 'data/**/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON Schema
        uses: snapcart/json-schema-validator@v1.0.0
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: data/schema.json
          json_path_pattern: data/*.json
          send_comment: true
          clear_comments: true
